### ISSUE TITLE
[QUESTION] Remove parts of the database schema by a TripleStore?

### ISSUE THREAD

**Issue by kinow** [Novartis/ontobrowser#2]
I read the database PDF, and noticed that the part about ontologies, some axioms, and maybe other parts have an overlap with built-in structure in Triple Stores such as Apache Jena.

This issue is more a brainstorm or question type. 

Would it be possible, and make sense, to replace certain tables by Apache Jena (or Virtuoso, StarDog, etc) and leverage from its solid data model, plus letting users query and integrate OntoBrowser via SPARQL?

**Comment by carloravagli** [comment]
The core ontology data structure is essentially a DAG so indeed lends itself well to being persisted in a triple store or graph database. I'm sure there are plenty of examples of this out there. 

With regards to OntoBrowser, it stores other types of non-DAG data e.g. cross references, synonyms, peer review workflow etc... OntoBrowser also maintains a Lucene index for searching. One potential issue with storing the DAG in a triple store (or graph database) and the other data in a RDBMS would be distributed transactions. Does Jena support XA transactions? For the Lucene index we had to write our own XAResource.

**Comment by kinow** [comment]
It is probably doable include Jena in a XA transaction, though I've never done that. I know that if you are using [TDB datastore](https://jena.apache.org/documentation/tdb/) you have transactions in SPARQL, and that you can do the same using Jena API. Maybe with something like the [TransactionHandler](https://jena.apache.org/documentation/javadoc/jena/com/hp/hpl/jena/graph/TransactionHandler.html).

Jena has a Lucene component ([jena-text](http://jena.apache.org/documentation/query/text-query.html)) that supports searching data in the triple store. It is under active development and probably will support [multi language](https://github.com/apache/jena/pull/64) and [better synchronization](https://github.com/apache/jena/pull/53) between Jena and Lucene.

I believe Virtuoso also provides some integration with Lucene, but I remember reading about it when gathering options for a project, but we decided to use Jena, so I'm not sure how that works with other triple stores.

**Comment by carloravagli** [comment]
Aside from providing a SPARQL endpoint, what other benefits would migrating to Jena offer?

**Comment by kinow** [comment]
Thinking well... not much :-) parts of the system could be abstracted into the triple store... a few tables removed, parts of the ontology could be handled by the triple store. I think the positive point would be exposing the data from OntoBrowser via SPARQL. The negative is to have another dependency in the system, having to maintain it... etc... unless you start Jena from your code embedded in OntoBrowser.

**Comment by carloravagli** [comment]
Proving a SPARQL endpoint for the ontology data could be a good addition. Having said that, we already expose the ontology data via a REST service that supports OWL (RDF and XML), OBO, Manchester and Turtle. There are also other REST services available to search the ontology data, expose child terms, expose synonyms and expose the SVG visualisation. I suppose if someone out there has a concrete requirement for SPARQL support then it might make sense to work with them to offer Jena (or similar) as an alternative storage option. My gut feeling however is that it would be less work to just expose a SPARQL endpoint (query only) on top of the existing database. There are off the shelf products to expose SPARQL endpoints for RDBMSs.

**Comment by kinow** [comment]
Fair points :) closing and leaving to someone else with better use cases to re-open.
