### ISSUE TITLE
Unable to load codelists

### ISSUE THREAD

**Issue by nikhitajatain** [Novartis/ontobrowser#4]
Good morning,

I am trying to load codelists in ontobrowser. it runs on port 8080 for me. I could not find an example of how to achieve this. Currently, I am trying this:
`$ curl -s -S -H "Content-Type: application/obo;charset=utf-8" -X PUT --data-binary "@send_codelist_terms.txt" -u SYSTEM "http://localhost:8080/ontobrowser/ontologies/sendcodelist"`

here my codelist is called send_codelist_terms.txt. Is it a correct way of achieving this?

Thank you,
Nikhita Jatain
Erasmus MC

**Comment by zbarry** [comment]
Hi @nikhitajatain - @carloravagli appears to be the only contributor to this repo (and I don't know anything about this project). I'm tagging him here to see if he can help, but it doesn't seem like he's been much active on GitHub recently.

**Comment by carloravagli** [comment]
Hi @nikhitajatain,

Currently OntoBrowser does not support loading flat code lists via the REST service i.e. only ontologies in OBO format can be loaded via REST. The reason for this is there is no standard file format for flat code lists. 

In the past we imported flat code lists (such as CDISC's controlled terminology) using standard ETL tools to populate the required tables i.e. ONTOLOGY, TERM, TERM_XREF and TERM_SYNONYM (optional) e.g. for Oracle we used SQL Loader. If you are using MySQL then you can use the LOAD DATA INFILE functionality. Note: you may need to preprocess the [SEND Terminology.txt](https://evs.nci.nih.gov/ftp1/CDISC/SEND/SEND%20Terminology.txt) file for MySQL's LOAD DATA INFILE.

Hope this helps,

Carlo

**Comment by nikhitajatain** [comment]
Many thanks Carlo,

This idea of codelist in obo format worked as you suggested. However, after uploading codelist as ontology, I had to manually set the is_codelist flag as TRUE in the database. is there a way to set it to true via the REST service?

Best,
Nikhita

**Comment by nikhitajatain** [comment]
Many Thanks Carlo,

Thank you very much for your suggestion. I am able to upload the obo file format of codelist into ontobrowser.

Best,
Nikhita
